[package]
name = "imy-core"
version = "0.1.0"
edition = "2018"

[dependencies]
tonic = "0.2.1"
diesel = "1.4.5"
prost = "0.6.1"
tokio = { version = "1.8.4", features = ["macros"] }
blake3 = "0.3.4"

[build-dependencies]
tonic-build = "0.2.0"
